# In this notebook we are going to cover some of the most fundamental concepts of tensors using TensorFlow

More specificall, we are going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tffunction ( a way to speed up our regular python functions )
* Using GPU with TensorFlow (or TPUs)
* Exercises to try for ourselves

# Introduction to tensors

In [ ]:
# Importing TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
 # Creating tensors with tf.constant()
 scaler = tf.constant(7)
 scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimentions of a tensor
scaler.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimention of the vector
vector.ndim

1

In [ ]:
# Create a matrix (matrix has more than one dimention)
matrix = tf.constant([[10, 8],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 7, 10]], dtype=int32)>

In [ ]:
#check the dimention of the matrix
matrix.ndim

2

In [ ]:
#Lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [3,4,5]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

##Creating tensors with tf.variable

In [ ]:
changable_tensor = tf.Variable([10, 7])


In [ ]:
changable_tensor[0].assign(9)
print(changable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>


#Creating random tensors

In [ ]:
#Random tensors are some arbitary size which contain random number.
random1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random1 = random1.normal(shape=(3,2))


In [ ]:
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random2 = random2.normal(shape=(3,2))

In [ ]:
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random1 == random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
# Shuffle the order of elements in a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
 tf.random.set_seed(42)
 tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Other ways of creating tensors. such as using numpy

In [ ]:
#Create a tensor of all ones
tf.ones([7,3])

<tf.Tensor: shape=(7, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor of all eros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Numpy  arrays into TensorFlow tensors
# The main difference between numpy arrays and TensorFlow tensors is that tensors can be run on a GPU(Much faster numerical computing)
import numpy as np
A = np.arange(1,25,dtype=np.int32)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
X = tf.constant(A, shape=(2,3,4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
X.ndim

3

#Getting information from tensors


In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimentions: ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Element along the 0 axis: ", rank_4_tensor[0].shape)
print("Element along the last axis: ", rank_4_tensor[-1].shape)
print("Total elements in our tensor: ", tf.size(rank_4_tensor).numpy())


Datatype of every element:  <dtype: 'float32'>
Number of dimentions:  4
Shape of tensor:  (2, 3, 4, 5)
Element along the 0 axis:  (3, 4, 5)
Element along the last axis:  (3, 4, 5)
Total elements in our tensor:  120


#Indexing tensors


In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10,7],
                             [2,4]])

In [ ]:
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [ ]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Adding extra dimention to our rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 4]]], dtype=int32)>

In [ ]:
rank_3_tensor.ndim

3

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis= -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis= 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis= 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 2,  4]]], dtype=int32)>

# Manupulating Tensors

In [ ]:
tensor = tf.constant([[10,8],
                      [5,7]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 5,  7]], dtype=int32)>

In [ ]:
 tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 18],
       [15, 17]], dtype=int32)>

In [ ]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -2],
       [-5, -3]], dtype=int32)>

In [ ]:
tensor *9

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[90, 72],
       [45, 63]], dtype=int32)>

In [ ]:
tf.multiply(tensor,9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[90, 72],
       [45, 63]], dtype=int32)>

In [ ]:
tf.add(tensor, 7)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 15],
       [12, 14]], dtype=int32)>

In [ ]:
tf.divide(tensor, 8)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1.25 , 1.   ],
       [0.625, 0.875]])>

In [ ]:
tf.subtract(tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 4],
       [1, 3]], dtype=int32)>

In [ ]:
# Multiplying matrices (tensors) 
# Matrix Multiplication
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[140, 136],
       [ 85,  89]], dtype=int32)>

In [ ]:
# Element wise
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  64],
       [ 25,  49]], dtype=int32)>

In [ ]:
# Python Matrix Multiplication
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[140, 136],
       [ 85,  89]], dtype=int32)>

In [ ]:
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
tf.shape

<function tensorflow.python.ops.array_ops.shape_v2>

In [ ]:
B = np.arange(0,12)
m = tf.constant(B,shape=(3,4))

In [ ]:
m

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [ ]:
tf.reshape(m, shape=(6,2))

<tf.Tensor: shape=(6, 2), dtype=int64, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])>

In [ ]:
tf.transpose(m)

<tf.Tensor: shape=(4, 3), dtype=int64, numpy=
array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])>

In [ ]:
tf.matmul(m, tf.transpose(m))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])>

In [ ]:
"""
Matrix multiplication is also referred to as Dot product
1. tf.matmul(tensor, tensor)
2. tf.tensordot(tensor,tensor)

both 1 and 2 are the same thing

"""
tf.tensordot(m, tf.transpose(m), axes=1)


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])>

# Changing the datatype of the tensor

In [ ]:
c = tf.constant([1.7,9.0])
c.dtype

tf.float32

In [ ]:
d = tf.constant([10,7])
d.dtype

tf.int32

In [ ]:
# float 32 to float 16
c = tf.cast(c,dtype=tf.float16)
c.dtype

tf.float16

In [ ]:
d = tf.cast(d, dtype=tf.int16)
d.dtype

tf.int16

In [ ]:
d

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([10,  7], dtype=int16)>

#Aggregating tensors

In [ ]:
# Aggegation = Condensing them from multiple values down to a smaller amount of values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# get the absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation
* Get the maximum
* Get the minimum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([91, 11,  2, 70, 95,  0,  4, 37, 15, 84, 80, 30, 56, 34, 92, 23, 33,
       47,  2, 70, 62, 25,  6, 64, 44, 22, 13, 90, 19, 38, 96,  9, 99, 82,
        4,  4, 95, 86, 31, 52, 76, 38, 19, 90, 79, 41, 96, 45, 25, 48])>

In [ ]:
E.shape, tf.size(E), E.ndim

(TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>, 1)

In [ ]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
np.min(E)

0

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
np.max(E)

99

In [ ]:
#Get the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2374>

In [ ]:
np.sum(E)

2374

In [ ]:
F = tf.constant(np.random.random(size=(1,50)))
F

<tf.Tensor: shape=(1, 50), dtype=float64, numpy=
array([[0.19210671, 0.162927  , 0.68425206, 0.64804084, 0.05212944,
        0.25825906, 0.07958911, 0.82058367, 0.56522101, 0.74509469,
        0.3963985 , 0.50396942, 0.33939543, 0.95643751, 0.38428122,
        0.42990932, 0.9606881 , 0.22166684, 0.77088416, 0.21320292,
        0.4455848 , 0.37716417, 0.44038613, 0.66590804, 0.10819628,
        0.27753155, 0.71300402, 0.84350322, 0.30443358, 0.51629665,
        0.52374152, 0.66652193, 0.76126718, 0.39482601, 0.97946418,
        0.54252832, 0.01951782, 0.36070308, 0.97333894, 0.03373536,
        0.83075175, 0.53202751, 0.69548032, 0.97898951, 0.1910368 ,
        0.64739023, 0.1173001 , 0.65957723, 0.14210494, 0.68077001]])>

In [ ]:
#Finding the standard deviation using tensorflow
tf.math.reduce_std(F).numpy()

0.2788514908708379

In [ ]:
tf.math.reduce_variance(F).numpy()

0.07775815396088899

In [ ]:
# To find the std of our tensor E we need to access tensorflow probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1037>

In [ ]:
# Now find the standard deviation
# tf.math.reduce_std(E) won't work
# because we our tensor to be dtype = float not integer
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=32.210087>

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32)).numpy()
# So we actually don't need to access tensorflow pron=bability

32.210087

#Find the positional maximum or minimum of a tensor

In [ ]:
# Create a new tensor for feeding positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
 # Find the positional maximum
 tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)
# No error

In [ ]:
# Finding the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
assert F[tf.argmin(F)] == tf.reduce_min(F)

#Squewing a tensor (Removing all single dimentions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

# One Hot Encoding Tensors

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] # Could be red,blue,green,purple
# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify customs values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [ ]:
tf.one_hot(some_list, depth=4, on_value="Y", off_value="X")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Y', b'X', b'X', b'X'],
       [b'X', b'Y', b'X', b'X'],
       [b'X', b'X', b'Y', b'X'],
       [b'X', b'X', b'X', b'Y']], dtype=object)>

# Squaring , log, square-root

In [ ]:
#Create a new tensor
H = tf.constant(np.arange(1,10))

In [ ]:
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float64)) # Method required non-int type

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float64))

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])>

# Tensors and Numpy
TensorFlow intaracts beautifuly with Numpy arrays

In [ ]:
# Creating a tensor directly from a numpy array
J = tf.Variable(np.array([3.,7.,10.]))

In [ ]:
J

<tf.Variable 'Variable:0' shape=(3,) dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# another method of converting tensors to a numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default type of each slighty different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# Check the data types of each
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

#Finding access to GPU

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri May 28 21:20:06 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0    28W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#Note: If you have access to a CUDA enabled GPU, TensorFlow will automatically use it whenever possible