In [ ]:
import numpy as np

##Data types and attributes of numpy

In [ ]:
# Numpy's main data type is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]]) 

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a1.shape

(3,)

In [ ]:
a2.shape

(2, 3)

In [ ]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [ ]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [ ]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [ ]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
# Create a dataframe from numpy array 
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [ ]:
#Must pass 2-d input. shape=(2, 3, 3)


##Creating numpy arrays

In [ ]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [ ]:
sample_array.dtype

dtype('int64')

In [ ]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
type(ones)

numpy.ndarray

In [ ]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[6, 0, 3, 1, 0],
       [6, 3, 1, 0, 7],
       [2, 6, 6, 4, 1]])

In [ ]:
random_array.size

15

In [ ]:
random_array.shape

(3, 5)

In [ ]:
random_array_2 = np.random.random(size=(5,3))
random_array_2

array([[0.61431759, 0.63246738, 0.99463906],
       [0.50828439, 0.01847725, 0.0727351 ],
       [0.0049496 , 0.84229032, 0.17148456],
       [0.54026879, 0.40912414, 0.20473569],
       [0.92759338, 0.5213349 , 0.06366868]])

In [ ]:
random_array_2.size

15

In [ ]:
random_array_2.shape

(5, 3)

In [ ]:
random_array_3 = np.random.rand(5,3,3)

In [ ]:
random_array_3

array([[[0.81137308, 0.69137126, 0.79852558],
        [0.24904971, 0.10128446, 0.21429785],
        [0.84991927, 0.49230034, 0.24578732]],

       [[0.57860643, 0.06484341, 0.19121698],
        [0.59672065, 0.75834898, 0.2570039 ],
        [0.56538013, 0.24344558, 0.05914626]],

       [[0.26163254, 0.89448908, 0.09173603],
        [0.47824086, 0.03177509, 0.49957827],
        [0.21803121, 0.71131936, 0.72847741]],

       [[0.23138473, 0.47734466, 0.29547147],
        [0.22818668, 0.32260971, 0.33333877],
        [0.58460516, 0.51566081, 0.95465151]],

       [[0.73747815, 0.63053013, 0.74705434],
        [0.64509646, 0.97752165, 0.31201973],
        [0.2465214 , 0.75426091, 0.18825364]]])

In [ ]:
#sudo random number
np.random.seed(1)
random_array_4 = np.random.randint(0,10,size=(5,3))
random_array_4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [ ]:
random_array_4.shape

(5, 3)

In [ ]:
np.random.seed(1)
random_array_5 = np.random.randint(0,10,size=(5,3))
random_array_5

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

##Viewing arrays and matrices

In [ ]:
np.unique(random_array_4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [ ]:
 a1

array([1, 2, 3])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a1[0]

1

In [ ]:
a2[0]

array([1. , 2. , 3.3])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3[:2 ,: 2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [ ]:
a4 = np.random.randint(0,10,size=(2,3,4,5))
a4

array([[[[2, 4, 7, 7, 9],
         [1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1],
         [0, 1, 8, 8, 3]],

        [[9, 8, 7, 3, 6],
         [5, 1, 9, 3, 4],
         [8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9]],

        [[2, 7, 7, 9, 8],
         [6, 9, 3, 7, 7],
         [4, 5, 9, 3, 6],
         [8, 0, 2, 7, 7]]],


       [[[9, 7, 3, 0, 8],
         [7, 7, 1, 1, 3],
         [0, 8, 6, 4, 5],
         [6, 2, 5, 7, 8]],

        [[4, 4, 7, 7, 4],
         [9, 0, 2, 0, 7],
         [1, 7, 9, 8, 4],
         [0, 1, 9, 8, 2]],

        [[3, 1, 2, 7, 2],
         [6, 0, 9, 2, 6],
         [6, 2, 7, 7, 0],
         [6, 5, 1, 4, 6]]]])

In [ ]:
a4.shape

(2, 3, 4, 5)

In [ ]:
a4.ndim

4

In [ ]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,:4]

array([[[[2, 4, 7, 7],
         [1, 7, 0, 6],
         [9, 7, 6, 9],
         [0, 1, 8, 8]],

        [[9, 8, 7, 3],
         [5, 1, 9, 3],
         [8, 1, 4, 0],
         [9, 2, 0, 4]],

        [[2, 7, 7, 9],
         [6, 9, 3, 7],
         [4, 5, 9, 3],
         [8, 0, 2, 7]]],


       [[[9, 7, 3, 0],
         [7, 7, 1, 1],
         [0, 8, 6, 4],
         [6, 2, 5, 7]],

        [[4, 4, 7, 7],
         [9, 0, 2, 0],
         [1, 7, 9, 8],
         [0, 1, 9, 8]],

        [[3, 1, 2, 7],
         [6, 0, 9, 2],
         [6, 2, 7, 7],
         [6, 5, 1, 4]]]])

##Manupulating and comparing arrays


In [ ]:
a1

array([1, 2, 3])

In [ ]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [ ]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [ ]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [ ]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [ ]:
np.sqrt(a3)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974],
        [2.64575131, 2.82842712, 3.        ]],

       [[3.16227766, 3.31662479, 3.46410162],
        [3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069]]])

In [ ]:
a1 % 2

array([1, 0, 1])

In [ ]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.log(a2)

array([[0.        , 0.69314718, 1.19392247],
       [1.38629436, 1.60943791, 1.87180218]])

In [ ]:
np.log10(a2)

array([[0.        , 0.30103   , 0.51851394],
       [0.60205999, 0.69897   , 0.81291336]])

In [ ]:
# aggregation = performing the same operation on anumber of things

massive_array = np.random.random(100000)

In [ ]:
massive_array.size

100000

In [ ]:
massive_array

array([5.27058102e-01, 8.85942099e-01, 3.57269760e-01, ...,
       8.26811457e-01, 2.61401389e-01, 5.04625277e-04])

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

100 loops, best of 5: 17.3 ms per loop
The slowest run took 9.33 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 48.8 µs per loop


In [ ]:
np.mean(a2)

3.6333333333333333

In [ ]:
np.max(a3)

18

In [ ]:
np.std(a2)

1.8226964152656422

In [ ]:
np.var(a2)

3.3222222222222224

In [ ]:
np.sqrt(np.var(a2))

1.8226964152656422

In [ ]:
#Reshaping numpy array
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
 a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
 a2_reshape = a2.reshape(2,3,1).shape

In [ ]:
a2_reshape * a3

array([[[ 2,  6,  3],
        [ 8, 15,  6],
        [14, 24,  9]],

       [[20, 33, 12],
        [26, 42, 15],
        [32, 51, 18]]])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.transpose().shape

(3, 2)

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a2.transpose()

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(0, 10, size=(5, 3))
mat2 = np.random.randint(0, 10, size=(5, 3))

In [ ]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [ ]:
# Element-wise multiplication
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [ ]:
mat3 = mat2.transpose()
print(mat3)
mat3.shape

[[6 8 9 4 3]
 [7 1 8 3 5]
 [7 5 9 0 0]]


(3, 5)

In [ ]:
# Dot product
np.dot(mat1, mat3)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [ ]:
np.random.seed(21)
sales_amount = np.random.randint(0,20,size=(5,3))
sales_amount

array([[ 9, 15,  4],
       [16, 16,  3],
       [ 2, 17, 10],
       [ 8, 14, 12],
       [ 9, 16, 14]])

In [ ]:
# Ceate weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amount, index= ["Mon","Tues","Wed","Thurs","Fri"], columns=["Almond butter","Peanut butter","Cashew butter"])

In [ ]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon                9             15              4
Tues              16             16              3
Wed                2             17             10
Thurs              8             14             12
Fri                9             16             14

In [ ]:
# Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [ ]:
#Create Butter Prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [ ]:
Total_sales = prices.dot(sales_amount.T)

In [ ]:
Total_sales

array([258, 324, 276, 336, 386])

In [ ]:
weekly_sales["Total ($)"] = Total_sales.transpose()

In [ ]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon                9             15              4        258
Tues              16             16              3        324
Wed                2             17             10        276
Thurs              8             14             12        336
Fri                9             16             14        386

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [ ]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [ ]:
type(bool_array)

numpy.ndarray

In [ ]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

#Sorting arrays

In [ ]:
random_array

array([[6, 0, 3, 1, 0],
       [6, 3, 1, 0, 7],
       [2, 6, 6, 4, 1]])

In [ ]:
# Sorting the numpy array *elements
np.sort(random_array)

array([[0, 0, 1, 3, 6],
       [0, 1, 3, 6, 7],
       [1, 2, 4, 6, 6]])

In [ ]:
# Sorting the indexes of the array elements
np.argsort(random_array)

array([[1, 4, 3, 2, 0],
       [3, 2, 1, 0, 4],
       [4, 0, 3, 1, 2]])

In [ ]:
# index of the minimum number
np.argmin(random_array)

1

In [ ]:
# index of the maximum number
np.argmax(random_array)

9

In [ ]:
# Practical example numpy in action

In [ ]:
from matplotlib.image import imread
panda = imread("/content/drive/MyDrive/TensorFlow2.0_certification/Data/Images_4_np/panda.png")

In [ ]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [ ]:
type(panda)

numpy.ndarray

In [ ]:
panda.shape

(2330, 3500, 3)

In [ ]:
panda.size, panda.ndim

(24465000, 3)